import Link from "@components/Link";
import { css, styled } from "@pigment-css/react";
import { PageMargin } from "@utils";
import { type Metadata } from "next";
import Image from "next/image";

export const metadata: Metadata = {
  title: "Credits - SnapFridge",
};

export default function Page() {
  return (
    <PageMargin>
      <h1 className={Title}>Credits</h1>
      <CreditList>
        <li>
          <p>
            Food Waste Picture by{" "}
            <Link href="https://reason.com/2022/04/23/californias-new-food-waste-law-is-backfiring/">
              Sarah Reingewirtz/ZUMA Press/Newscom
            </Link>
          </p>
          <Image
            width={1704}
            height={1704}
            className={ImageCSS}
            src="/Landfill.png"
            alt="Landfill worker clearing through a landfill of fruit waste"
            quality={45}
            sizes={`50vw`}
          />
        </li>
        <li>
          <p>
            Fridge Picture by{" "}
            <Link href="https://shop.sharpusa.com/sharp-24-in-bottom-freezer-counter-depth-refrigerator-sjb1255gs/">
              Sharp Electronics Corporation
            </Link>
          </p>
          <Image
            src="/Fridge.avif"
            width={2417}
            height={2814}
            alt="Fridge filled with food inside"
            sizes={`50vw`}
          />
        </li>
        <li>
          <p>
            Privacy Policy Generated by{" "}
            <Link href="https://www.termsfeed.com/privacy-policy-generator/">
              TermsFeed
            </Link>
          </p>
        </li>
      </CreditList>
    </PageMargin>
  );
}

const Title = css({
  alignSelf: "center",
});

const CreditList = styled("ul")({
  alignItems: "center",

  "& > li": {
    margin: "32px 0 0",
    justifyItems: "center",
  },

  "& > li > img": {
    width: "50%",
    height: "auto",
  },
});

const ImageCSS = css({
  borderRadius: "6px",
});
