import Image from "next/image";
import Link from "@components/Link";
import { styled, css } from "@pigment-css/react";

function Page() {
  return (
    <>
      <h1 className={Title}>Credits</h1>
      <CreditList>
        <li>
          <p>Food Waste Picture by <Link href="https://reason.com/2022/04/23/californias-new-food-waste-law-is-backfiring/">Sarah Reingewirtz/ZUMA Press/Newscom</Link></p>
          <Image 
            width={692}
            height={689}
            src="/Landfill.png"
            alt="A landfill worker in a neon vest clearing through a landfill of fruit waste"
            className={ImageCSS}
          />
        </li>
        <li>
          <p>Fridge Picture by <Link href="https://shop.sharpusa.com/sharp-24-in-bottom-freezer-counter-depth-refrigerator-sjb1255gs/">Sharp Electronics Corporation</Link></p>
          <Image 
            src="/Fridge.png"
            width={415}
            height={483}
            alt="Fridge filled with food inside"
          />
        </li>
        <li>
          <p>Icons by <Link href="https://lucide.dev/">Lucide React</Link></p>
        </li>
        <li>
          <p>Food/Recipe API by <Link href="https://spoonacular.com/food-api">Spoonacular</Link></p>
        </li>
        <li>
          <p>Privacy Policy Generated by <Link href="https://www.termsfeed.com/privacy-policy-generator/">TermsFeed</Link></p>
        </li>
      </CreditList>
    </>
  )
}

const Title = css({
  alignSelf: "center",
});

const CreditList = styled('ul')({
  padding: 0,
  listStyleType: "none",
  alignItems: "center",
  "&> li": {
    marginTop: "32px",
    justifyItems: "center",
  }
});

const ImageCSS = css({
  borderRadius: "6px",
});

export default Page;