import Image from "next/image";
import Link from "@components/Link";
import { styled, css } from "@pigment-css/react";
import { PageMargin } from "@components/Global";

export default function Page() {
  return (
    <PageMargin>
      <h1 className={Title}>Credits</h1>
      <CreditList>
        <li>
          <p>
            Food Waste Picture by{" "}
            <Link href="https://reason.com/2022/04/23/californias-new-food-waste-law-is-backfiring/">
              Sarah Reingewirtz/ZUMA Press/Newscom
            </Link>
          </p>
          <Image
            width={1704}
            height={1704}
            src="/Landfill.avif"
            alt="A landfill worker in a neon vest clearing through a landfill of fruit waste"
            className={ImageCSS}
          />
        </li>
        <li>
          <p>
            Fridge Picture by{" "}
            <Link href="https://shop.sharpusa.com/sharp-24-in-bottom-freezer-counter-depth-refrigerator-sjb1255gs/">
              Sharp Electronics Corporation
            </Link>
          </p>
          <Image
            src="/Fridge.avif"
            width={2417}
            height={2814}
            alt="Fridge filled with food inside"
          />
        </li>
        <li>
          <p>
            Icons by <Link href="https://lucide.dev/">Lucide React</Link>
          </p>
        </li>
        <li>
          <p>
            Food/Recipe API by{" "}
            <Link href="https://spoonacular.com/food-api">Spoonacular</Link>
          </p>
        </li>
        <li>
          <p>
            Privacy Policy Generated by{" "}
            <Link href="https://www.termsfeed.com/privacy-policy-generator/">
              TermsFeed
            </Link>
          </p>
        </li>
      </CreditList>
    </PageMargin>
  );
}

const Title = css({
  alignSelf: "center"
});

const CreditList = styled("ul")({
  padding: 0,
  listStyleType: "none",
  alignItems: "center",

  "&> li": {
    marginTop: "32px",
    justifyItems: "center"
  },

  "&> li > img": {
    width: "50%",
    height: "auto"
  }
});

const ImageCSS = css({
  borderRadius: "6px"
});
