import "@pigment-css/react/styles.css";
import "./globalStyles";
import { Poppins } from "next/font/google";
import ThemeProvider from "./providers";
import NavBar from "@components/NavBar";
import Footer from "@components/Footer";
import { styled } from "@pigment-css/react";

const poppins = Poppins({
  weight: ["400", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={poppins.className} suppressHydrationWarning>
      <body>
        {/* theme provider from next-themes, handles the dark/light theming */}
        <ThemeProvider
          attribute="data-theme"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Background>
            <NavBar></NavBar>
            <Main>{children}</Main>
            <Footer></Footer>
          </Background>
        </ThemeProvider>
      </body>
    </html>
  );
}

const Background = styled("div")({
  display: "flex",
  flexDirection: "column",
  background: `
      radial-gradient(circle at top left, #969FCB 0%, #194D5A 63%, #041514 100%),
      linear-gradient(#535353 0%, #10423f 96%, #000000 100%)
    `,
  backgroundBlendMode: "multiply", // or 'overlay', 'screen', etc.
  minHeight: "100%",
});

const Main = styled("main")({
  flex: 1,
});
