import type { Recipe } from "@components/Global";

const recipesExample: Recipe[] = [
  {
    id: 639637,
    title: "Classic scones",
    image: "https://img.spoonacular.com/recipes/639637-312x231.jpg",
    imageType: "jpg",
    usedIngredientCount: 3,
    missedIngredientCount: 0,
    missedIngredients: [],
    usedIngredients: [
      {
        id: 1077,
        amount: 0.75,
        unit: "cup",
        unitLong: "cups",
        unitShort: "cup",
        aisle: "Milk, Eggs, Other Dairy",
        name: "milk",
        original: "3/4 cup milk",
        originalName: "milk",
        meta: [],
        image: "https://img.spoonacular.com/ingredients_100x100/milk.png",
      },
      {
        id: 10819297,
        amount: 4,
        unit: "servings",
        unitLong: "servings",
        unitShort: "servings",
        aisle: "Nut butters, Jams, and Honey",
        name: "strawberry jam and cream",
        original: "strawberry jam and cream, for serving",
        originalName: "strawberry jam and cream, for serving",
        meta: ["for serving"],
        image: "https://img.spoonacular.com/ingredients_100x100/strawberry-jam.png",
      },
      {
        id: 1145,
        amount: 50,
        unit: "g",
        unitLong: "grams",
        unitShort: "g",
        aisle: "Milk, Eggs, Other Dairy",
        name: "butter",
        original: "50g unsalted butter, softened",
        originalName: "unsalted butter, softened",
        meta: ["unsalted", "softened"],
        extendedName: "unsalted butter",
        image: "https://img.spoonacular.com/ingredients_100x100/butter-sliced.jpg",
      },
    ],
    unusedIngredients: [
      {
        id: 1123,
        amount: 1,
        unit: "serving",
        unitLong: "serving",
        unitShort: "serving",
        aisle: "Milk, Eggs, Other Dairy",
        name: "egg",
        original: "egg",
        originalName: "egg",
        meta: [],
        image: "https://img.spoonacular.com/ingredients_100x100/egg.png",
      },
      {
        id: 11124,
        amount: 1,
        unit: "serving",
        unitLong: "serving",
        unitShort: "serving",
        aisle: "Produce",
        name: "carrots",
        original: "carrots",
        originalName: "carrots",
        meta: [],
        image: "https://img.spoonacular.com/ingredients_100x100/sliced-carrot.png",
      },
      {
        id: 11935,
        amount: 1,
        unit: "serving",
        unitLong: "serving",
        unitShort: "serving",
        aisle: "Condiments",
        name: "ketchup",
        original: "ketchup",
        originalName: "ketchup",
        meta: [],
        image: "https://img.spoonacular.com/ingredients_100x100/ketchup.png",
      },
    ],
    likes: 359,
  },
  {
    id: 716407,
    title: "Simple Whole Wheat Crepes",
    image: "https://img.spoonacular.com/recipes/716407-312x231.jpg",
    imageType: "jpg",
    usedIngredientCount: 3,
    missedIngredientCount: 1,
    missedIngredients: [
      {
        id: 19911,
        amount: 1,
        unit: "Tablespoon",
        unitLong: "Tablespoon",
        unitShort: "Tbsp",
        aisle: "Cereal",
        name: "maple syrup",
        original: "1 Tablespoon maple syrup (optional)",
        originalName: "maple syrup (optional)",
        meta: [],
        image: "https://img.spoonacular.com/ingredients_100x100/maple-syrup.png",
      },
    ],
    usedIngredients: [
      {
        id: 1001,
        amount: 3,
        unit: "Tablespoons",
        unitLong: "Tablespoons",
        unitShort: "Tbsp",
        aisle: "Milk, Eggs, Other Dairy",
        name: "butter",
        original: "3 Tablespoons butter, melted",
        originalName: "butter, melted",
        meta: ["melted"],
        image: "https://img.spoonacular.com/ingredients_100x100/butter-sliced.jpg",
      },
      {
        id: 1123,
        amount: 3,
        unit: "",
        unitLong: "",
        unitShort: "",
        aisle: "Milk, Eggs, Other Dairy",
        name: "eggs",
        original: "3 eggs",
        originalName: "eggs",
        meta: [],
        image: "https://img.spoonacular.com/ingredients_100x100/egg.png",
      },
      {
        id: 1077,
        amount: 1,
        unit: "cup",
        unitLong: "cup",
        unitShort: "cup",
        aisle: "Milk, Eggs, Other Dairy",
        name: "milk",
        original: "1 cup milk",
        originalName: "milk",
        meta: [],
        image: "https://img.spoonacular.com/ingredients_100x100/milk.png",
      },
    ],
    unusedIngredients: [
      {
        id: 10819297,
        amount: 1,
        unit: "serving",
        unitLong: "serving",
        unitShort: "serving",
        aisle: "Nut butters, Jams, and Honey",
        name: "strawberry jam",
        original: "strawberry jam",
        originalName: "strawberry jam",
        meta: [],
        image: "https://img.spoonacular.com/ingredients_100x100/strawberry-jam.png",
      },
      {
        id: 11124,
        amount: 1,
        unit: "serving",
        unitLong: "serving",
        unitShort: "serving",
        aisle: "Produce",
        name: "carrots",
        original: "carrots",
        originalName: "carrots",
        meta: [],
        image: "https://img.spoonacular.com/ingredients_100x100/sliced-carrot.png",
      },
      {
        id: 11935,
        amount: 1,
        unit: "serving",
        unitLong: "serving",
        unitShort: "serving",
        aisle: "Condiments",
        name: "ketchup",
        original: "ketchup",
        originalName: "ketchup",
        meta: [],
        image: "https://img.spoonacular.com/ingredients_100x100/ketchup.png",
      },
    ],
    likes: 109,
  },
  {
    id: 641759,
    title: "Dutch Baby",
    image: "https://img.spoonacular.com/recipes/641759-312x231.jpg",
    imageType: "jpg",
    usedIngredientCount: 3,
    missedIngredientCount: 1,
    missedIngredients: [
      {
        id: 9150,
        amount: 2,
        unit: "",
        unitLong: "",
        unitShort: "",
        aisle: "Produce",
        name: "lemons",
        original: "2 lemons",
        originalName: "lemons",
        meta: [],
        image: "https://img.spoonacular.com/ingredients_100x100/lemon.png",
      },
    ],
    usedIngredients: [
      {
        id: 1123,
        amount: 3,
        unit: "",
        unitLong: "",
        unitShort: "",
        aisle: "Milk, Eggs, Other Dairy",
        name: "eggs",
        original: "3 Eggs",
        originalName: "Eggs",
        meta: [],
        image: "https://img.spoonacular.com/ingredients_100x100/egg.png",
      },
      {
        id: 1077,
        amount: 1,
        unit: "cup",
        unitLong: "cup",
        unitShort: "cup",
        aisle: "Milk, Eggs, Other Dairy",
        name: "milk",
        original: "1 cup milk",
        originalName: "milk",
        meta: [],
        image: "https://img.spoonacular.com/ingredients_100x100/milk.png",
      },
      {
        id: 1145,
        amount: 2,
        unit: "tablespoons",
        unitLong: "tablespoons",
        unitShort: "Tbsp",
        aisle: "Milk, Eggs, Other Dairy",
        name: "butter",
        original: "2 tablespoons Unsalted Organic Butter",
        originalName: "Unsalted Organic Butter",
        meta: ["unsalted", "organic"],
        extendedName: "unsalted butter",
        image: "https://img.spoonacular.com/ingredients_100x100/butter-sliced.jpg",
      },
    ],
    unusedIngredients: [
      {
        id: 10819297,
        amount: 1,
        unit: "serving",
        unitLong: "serving",
        unitShort: "serving",
        aisle: "Nut butters, Jams, and Honey",
        name: "strawberry jam",
        original: "strawberry jam",
        originalName: "strawberry jam",
        meta: [],
        image: "https://img.spoonacular.com/ingredients_100x100/strawberry-jam.png",
      },
      {
        id: 11124,
        amount: 1,
        unit: "serving",
        unitLong: "serving",
        unitShort: "serving",
        aisle: "Produce",
        name: "carrots",
        original: "carrots",
        originalName: "carrots",
        meta: [],
        image: "https://img.spoonacular.com/ingredients_100x100/sliced-carrot.png",
      },
      {
        id: 11935,
        amount: 1,
        unit: "serving",
        unitLong: "serving",
        unitShort: "serving",
        aisle: "Condiments",
        name: "ketchup",
        original: "ketchup",
        originalName: "ketchup",
        meta: [],
        image: "https://img.spoonacular.com/ingredients_100x100/ketchup.png",
      },
    ],
    likes: 22,
  },
  {
    id: 649593,
    title: "Lemon Cupcakes",
    image: "https://img.spoonacular.com/recipes/649593-312x231.jpg",
    imageType: "jpg",
    usedIngredientCount: 3,
    missedIngredientCount: 1,
    missedIngredients: [
      {
        id: 9156,
        amount: 2.5,
        unit: "teaspoons",
        unitLong: "teaspoons",
        unitShort: "tsp",
        aisle: "Produce",
        name: "lemon zest",
        original: "2 1/2 teaspoons Freshly-grated lemon zest",
        originalName: "Freshly-grated lemon zest",
        meta: ["freshly-grated"],
        image: "https://img.spoonacular.com/ingredients_100x100/zest-lemon.jpg",
      },
    ],
    usedIngredients: [
      {
        id: 1123,
        amount: 2,
        unit: "",
        unitLong: "",
        unitShort: "",
        aisle: "Milk, Eggs, Other Dairy",
        name: "eggs",
        original: "2 eggs",
        originalName: "eggs",
        meta: [],
        image: "https://img.spoonacular.com/ingredients_100x100/egg.png",
      },
      {
        id: 1077,
        amount: 0.75,
        unit: "cup",
        unitLong: "cups",
        unitShort: "cup",
        aisle: "Milk, Eggs, Other Dairy",
        name: "milk",
        original: "3/4 cup milk",
        originalName: "milk",
        meta: [],
        image: "https://img.spoonacular.com/ingredients_100x100/milk.png",
      },
      {
        id: 1145,
        amount: 10,
        unit: "tablespoons",
        unitLong: "tablespoons",
        unitShort: "Tbsp",
        aisle: "Milk, Eggs, Other Dairy",
        name: "butter",
        original: "10 tablespoons unsalted butter",
        originalName: "unsalted butter",
        meta: ["unsalted"],
        extendedName: "unsalted butter",
        image: "https://img.spoonacular.com/ingredients_100x100/butter-sliced.jpg",
      },
    ],
    unusedIngredients: [
      {
        id: 10819297,
        amount: 1,
        unit: "serving",
        unitLong: "serving",
        unitShort: "serving",
        aisle: "Nut butters, Jams, and Honey",
        name: "strawberry jam",
        original: "strawberry jam",
        originalName: "strawberry jam",
        meta: [],
        image: "https://img.spoonacular.com/ingredients_100x100/strawberry-jam.png",
      },
      {
        id: 11124,
        amount: 1,
        unit: "serving",
        unitLong: "serving",
        unitShort: "serving",
        aisle: "Produce",
        name: "carrots",
        original: "carrots",
        originalName: "carrots",
        meta: [],
        image: "https://img.spoonacular.com/ingredients_100x100/sliced-carrot.png",
      },
      {
        id: 11935,
        amount: 1,
        unit: "serving",
        unitLong: "serving",
        unitShort: "serving",
        aisle: "Condiments",
        name: "ketchup",
        original: "ketchup",
        originalName: "ketchup",
        meta: [],
        image: "https://img.spoonacular.com/ingredients_100x100/ketchup.png",
      },
    ],
    likes: 1,
  },
  {
    id: 649609,
    title: "Lemon Delicious Pudding",
    image: "https://img.spoonacular.com/recipes/649609-312x231.jpg",
    imageType: "jpg",
    usedIngredientCount: 3,
    missedIngredientCount: 1,
    missedIngredients: [
      {
        id: 9150,
        amount: 2,
        unit: "",
        unitLong: "",
        unitShort: "",
        aisle: "Produce",
        name: "lemons",
        original: "2 lemons",
        originalName: "lemons",
        meta: [],
        image: "https://img.spoonacular.com/ingredients_100x100/lemon.png",
      },
    ],
    usedIngredients: [
      {
        id: 1001,
        amount: 60,
        unit: "grams",
        unitLong: "grams",
        unitShort: "g",
        aisle: "Milk, Eggs, Other Dairy",
        name: "butter",
        original: "60 grams butter",
        originalName: "butter",
        meta: [],
        image: "https://img.spoonacular.com/ingredients_100x100/butter-sliced.jpg",
      },
      {
        id: 1123,
        amount: 3,
        unit: "",
        unitLong: "",
        unitShort: "",
        aisle: "Milk, Eggs, Other Dairy",
        name: "eggs",
        original: "3 Eggs",
        originalName: "Eggs",
        meta: [],
        image: "https://img.spoonacular.com/ingredients_100x100/egg.png",
      },
      {
        id: 1077,
        amount: 1.5,
        unit: "cups",
        unitLong: "cups",
        unitShort: "cup",
        aisle: "Milk, Eggs, Other Dairy",
        name: "milk",
        original: "1 1/2 cups milk",
        originalName: "milk",
        meta: [],
        image: "https://img.spoonacular.com/ingredients_100x100/milk.png",
      },
    ],
    unusedIngredients: [
      {
        id: 10819297,
        amount: 1,
        unit: "serving",
        unitLong: "serving",
        unitShort: "serving",
        aisle: "Nut butters, Jams, and Honey",
        name: "strawberry jam",
        original: "strawberry jam",
        originalName: "strawberry jam",
        meta: [],
        image: "https://img.spoonacular.com/ingredients_100x100/strawberry-jam.png",
      },
      {
        id: 11124,
        amount: 1,
        unit: "serving",
        unitLong: "serving",
        unitShort: "serving",
        aisle: "Produce",
        name: "carrots",
        original: "carrots",
        originalName: "carrots",
        meta: [],
        image: "https://img.spoonacular.com/ingredients_100x100/sliced-carrot.png",
      },
      {
        id: 11935,
        amount: 1,
        unit: "serving",
        unitLong: "serving",
        unitShort: "serving",
        aisle: "Condiments",
        name: "ketchup",
        original: "ketchup",
        originalName: "ketchup",
        meta: [],
        image: "https://img.spoonacular.com/ingredients_100x100/ketchup.png",
      },
    ],
    likes: 1,
  },
  {
    id: 991625,
    title: "Nutella Buttercream Cupcakes with Hidden Cadbury Egg",
    image: "https://img.spoonacular.com/recipes/991625-312x231.jpg",
    imageType: "jpg",
    usedIngredientCount: 2,
    missedIngredientCount: 1,
    missedIngredients: [
      {
        id: 1052050,
        amount: 1,
        unit: "tsp",
        unitLong: "teaspoon",
        unitShort: "tsp",
        aisle: "Baking",
        name: "vanilla",
        original: "1 tsp of vanilla,",
        originalName: "vanilla",
        meta: [],
        image: "https://img.spoonacular.com/ingredients_100x100/vanilla.jpg",
      },
    ],
    usedIngredients: [
      {
        id: 1123,
        amount: 4,
        unit: "",
        unitLong: "",
        unitShort: "",
        aisle: "Milk, Eggs, Other Dairy",
        name: "eggs",
        original: "4 eggs",
        originalName: "eggs",
        meta: [],
        image: "https://img.spoonacular.com/ingredients_100x100/egg.png",
      },
      {
        id: 1077,
        amount: 1,
        unit: "cup",
        unitLong: "cup",
        unitShort: "cup",
        aisle: "Milk, Eggs, Other Dairy",
        name: "milk",
        original: "1 cup of milk,",
        originalName: "milk",
        meta: [],
        image: "https://img.spoonacular.com/ingredients_100x100/milk.png",
      },
    ],
    unusedIngredients: [
      {
        id: 10819297,
        amount: 1,
        unit: "serving",
        unitLong: "serving",
        unitShort: "serving",
        aisle: "Nut butters, Jams, and Honey",
        name: "strawberry jam",
        original: "strawberry jam",
        originalName: "strawberry jam",
        meta: [],
        image: "https://img.spoonacular.com/ingredients_100x100/strawberry-jam.png",
      },
      {
        id: 1001,
        amount: 1,
        unit: "serving",
        unitLong: "serving",
        unitShort: "serving",
        aisle: "Milk, Eggs, Other Dairy",
        name: "butter",
        original: "butter",
        originalName: "butter",
        meta: [],
        image: "https://img.spoonacular.com/ingredients_100x100/butter-sliced.jpg",
      },
      {
        id: 11124,
        amount: 1,
        unit: "serving",
        unitLong: "serving",
        unitShort: "serving",
        aisle: "Produce",
        name: "carrots",
        original: "carrots",
        originalName: "carrots",
        meta: [],
        image: "https://img.spoonacular.com/ingredients_100x100/sliced-carrot.png",
      },
      {
        id: 11935,
        amount: 1,
        unit: "serving",
        unitLong: "serving",
        unitShort: "serving",
        aisle: "Condiments",
        name: "ketchup",
        original: "ketchup",
        originalName: "ketchup",
        meta: [],
        image: "https://img.spoonacular.com/ingredients_100x100/ketchup.png",
      },
    ],
    likes: 14,
  },
  {
    id: 635964,
    title: "Bread Omlette",
    image: "https://img.spoonacular.com/recipes/635964-312x231.jpg",
    imageType: "jpg",
    usedIngredientCount: 2,
    missedIngredientCount: 1,
    missedIngredients: [
      {
        id: 18079,
        amount: 1,
        unit: "cup",
        unitLong: "cup",
        unitShort: "cup",
        aisle: "Pasta and Rice",
        name: "bread crumbs",
        original: "1 cup Fresh bread crumbs",
        originalName: "Fresh bread crumbs",
        meta: ["fresh"],
        extendedName: "fresh bread crumbs",
        image: "https://img.spoonacular.com/ingredients_100x100/breadcrumbs.jpg",
      },
    ],
    usedIngredients: [
      {
        id: 1123,
        amount: 4,
        unit: "",
        unitLong: "",
        unitShort: "",
        aisle: "Milk, Eggs, Other Dairy",
        name: "eggs",
        original: "4 Eggs",
        originalName: "Eggs",
        meta: [],
        image: "https://img.spoonacular.com/ingredients_100x100/egg.png",
      },
      {
        id: 1077,
        amount: 1,
        unit: "cup",
        unitLong: "cup",
        unitShort: "cup",
        aisle: "Milk, Eggs, Other Dairy",
        name: "milk",
        original: "1 cup Boiled milk",
        originalName: "Boiled milk",
        meta: ["boiled"],
        extendedName: "cooked milk",
        image: "https://img.spoonacular.com/ingredients_100x100/milk.png",
      },
    ],
    unusedIngredients: [
      {
        id: 10819297,
        amount: 1,
        unit: "serving",
        unitLong: "serving",
        unitShort: "serving",
        aisle: "Nut butters, Jams, and Honey",
        name: "strawberry jam",
        original: "strawberry jam",
        originalName: "strawberry jam",
        meta: [],
        image: "https://img.spoonacular.com/ingredients_100x100/strawberry-jam.png",
      },
      {
        id: 1001,
        amount: 1,
        unit: "serving",
        unitLong: "serving",
        unitShort: "serving",
        aisle: "Milk, Eggs, Other Dairy",
        name: "butter",
        original: "butter",
        originalName: "butter",
        meta: [],
        image: "https://img.spoonacular.com/ingredients_100x100/butter-sliced.jpg",
      },
      {
        id: 11124,
        amount: 1,
        unit: "serving",
        unitLong: "serving",
        unitShort: "serving",
        aisle: "Produce",
        name: "carrots",
        original: "carrots",
        originalName: "carrots",
        meta: [],
        image: "https://img.spoonacular.com/ingredients_100x100/sliced-carrot.png",
      },
      {
        id: 11935,
        amount: 1,
        unit: "serving",
        unitLong: "serving",
        unitShort: "serving",
        aisle: "Condiments",
        name: "ketchup",
        original: "ketchup",
        originalName: "ketchup",
        meta: [],
        image: "https://img.spoonacular.com/ingredients_100x100/ketchup.png",
      },
    ],
    likes: 1,
  },
  {
    id: 633574,
    title: "Baked Custard",
    image: "https://img.spoonacular.com/recipes/633574-312x231.jpg",
    imageType: "jpg",
    usedIngredientCount: 2,
    missedIngredientCount: 1,
    missedIngredients: [
      {
        id: 1052050,
        amount: 0.5,
        unit: "teaspoon",
        unitLong: "teaspoons",
        unitShort: "tsp",
        aisle: "Baking",
        name: "vanilla",
        original: "1/2 teaspoon vanilla",
        originalName: "vanilla",
        meta: [],
        image: "https://img.spoonacular.com/ingredients_100x100/vanilla.jpg",
      },
    ],
    usedIngredients: [
      {
        id: 1123,
        amount: 4,
        unit: "",
        unitLong: "",
        unitShort: "",
        aisle: "Milk, Eggs, Other Dairy",
        name: "eggs",
        original: "4 eggs",
        originalName: "eggs",
        meta: [],
        image: "https://img.spoonacular.com/ingredients_100x100/egg.png",
      },
      {
        id: 1077,
        amount: 2,
        unit: "cups",
        unitLong: "cups",
        unitShort: "cup",
        aisle: "Milk, Eggs, Other Dairy",
        name: "milk",
        original: "2 cups milk, scalded",
        originalName: "milk, scalded",
        meta: [],
        image: "https://img.spoonacular.com/ingredients_100x100/milk.png",
      },
    ],
    unusedIngredients: [
      {
        id: 10819297,
        amount: 1,
        unit: "serving",
        unitLong: "serving",
        unitShort: "serving",
        aisle: "Nut butters, Jams, and Honey",
        name: "strawberry jam",
        original: "strawberry jam",
        originalName: "strawberry jam",
        meta: [],
        image: "https://img.spoonacular.com/ingredients_100x100/strawberry-jam.png",
      },
      {
        id: 1001,
        amount: 1,
        unit: "serving",
        unitLong: "serving",
        unitShort: "serving",
        aisle: "Milk, Eggs, Other Dairy",
        name: "butter",
        original: "butter",
        originalName: "butter",
        meta: [],
        image: "https://img.spoonacular.com/ingredients_100x100/butter-sliced.jpg",
      },
      {
        id: 11124,
        amount: 1,
        unit: "serving",
        unitLong: "serving",
        unitShort: "serving",
        aisle: "Produce",
        name: "carrots",
        original: "carrots",
        originalName: "carrots",
        meta: [],
        image: "https://img.spoonacular.com/ingredients_100x100/sliced-carrot.png",
      },
      {
        id: 11935,
        amount: 1,
        unit: "serving",
        unitLong: "serving",
        unitShort: "serving",
        aisle: "Condiments",
        name: "ketchup",
        original: "ketchup",
        originalName: "ketchup",
        meta: [],
        image: "https://img.spoonacular.com/ingredients_100x100/ketchup.png",
      },
    ],
    likes: 1,
  },
  {
    id: 635492,
    title: "Blueberry Loaf With Blueberry Syrup",
    image: "https://img.spoonacular.com/recipes/635492-312x231.jpg",
    imageType: "jpg",
    usedIngredientCount: 3,
    missedIngredientCount: 2,
    missedIngredients: [
      {
        id: 9050,
        amount: 3,
        unit: "cups",
        unitLong: "cups",
        unitShort: "cup",
        aisle: "Produce",
        name: "blueberries",
        original: "3 cups Blueberries",
        originalName: "Blueberries",
        meta: [],
        image: "https://img.spoonacular.com/ingredients_100x100/blueberries.jpg",
      },
      {
        id: 9156,
        amount: 1,
        unit: "teaspoon",
        unitLong: "teaspoon",
        unitShort: "tsp",
        aisle: "Produce",
        name: "lemon zest",
        original: "1 teaspoon lemon zest",
        originalName: "lemon zest",
        meta: [],
        image: "https://img.spoonacular.com/ingredients_100x100/zest-lemon.jpg",
      },
    ],
    usedIngredients: [
      {
        id: 1001,
        amount: 0.5,
        unit: "tablespoon",
        unitLong: "tablespoons",
        unitShort: "Tbsp",
        aisle: "Milk, Eggs, Other Dairy",
        name: "butter",
        original: "1/2 tablespoon stick butter softened, plus 1 for greasing the pan",
        originalName: "butter softened, plus 1 for greasing the pan",
        meta: ["softened", "for greasing the pan"],
        image: "https://img.spoonacular.com/ingredients_100x100/butter-sliced.jpg",
      },
      {
        id: 1123,
        amount: 2,
        unit: "large",
        unitLong: "larges",
        unitShort: "large",
        aisle: "Milk, Eggs, Other Dairy",
        name: "eggs",
        original: "2 large eggs",
        originalName: "eggs",
        meta: [],
        image: "https://img.spoonacular.com/ingredients_100x100/egg.png",
      },
      {
        id: 1077,
        amount: 0.75,
        unit: "cup",
        unitLong: "cups",
        unitShort: "cup",
        aisle: "Milk, Eggs, Other Dairy",
        name: "milk",
        original: "3/4 cup milk",
        originalName: "milk",
        meta: [],
        image: "https://img.spoonacular.com/ingredients_100x100/milk.png",
      },
    ],
    unusedIngredients: [
      {
        id: 10819297,
        amount: 1,
        unit: "serving",
        unitLong: "serving",
        unitShort: "serving",
        aisle: "Nut butters, Jams, and Honey",
        name: "strawberry jam",
        original: "strawberry jam",
        originalName: "strawberry jam",
        meta: [],
        image: "https://img.spoonacular.com/ingredients_100x100/strawberry-jam.png",
      },
      {
        id: 11124,
        amount: 1,
        unit: "serving",
        unitLong: "serving",
        unitShort: "serving",
        aisle: "Produce",
        name: "carrots",
        original: "carrots",
        originalName: "carrots",
        meta: [],
        image: "https://img.spoonacular.com/ingredients_100x100/sliced-carrot.png",
      },
      {
        id: 11935,
        amount: 1,
        unit: "serving",
        unitLong: "serving",
        unitShort: "serving",
        aisle: "Condiments",
        name: "ketchup",
        original: "ketchup",
        originalName: "ketchup",
        meta: [],
        image: "https://img.spoonacular.com/ingredients_100x100/ketchup.png",
      },
    ],
    likes: 1,
  },
  {
    id: 654055,
    title: "Organic Pumpkin Whoopie Pies",
    image: "https://img.spoonacular.com/recipes/654055-312x231.jpg",
    imageType: "jpg",
    usedIngredientCount: 3,
    missedIngredientCount: 2,
    missedIngredients: [
      {
        id: 11424,
        amount: 1,
        unit: "cup",
        unitLong: "cup",
        unitShort: "cup",
        aisle: "Baking",
        name: "pumpkin puree",
        original: "1 cup canned pumpkin puree (use organic if you can find it!)",
        originalName: "canned pumpkin puree (use organic if you can find it!)",
        meta: ["organic", "canned", "(use if you can find it!)"],
        extendedName: "canned pumpkin puree",
        image: "https://img.spoonacular.com/ingredients_100x100/pumpkin-puree.jpg",
      },
      {
        id: 10018137,
        amount: 1,
        unit: "package",
        unitLong: "package",
        unitShort: "pkg",
        aisle: "Baking",
        name: "spiced cake mix",
        original: "1 package spiced cake mix",
        originalName: "spiced cake mix",
        meta: [],
        image: "https://img.spoonacular.com/ingredients_100x100/null",
      },
    ],
    usedIngredients: [
      {
        id: 1001,
        amount: 1,
        unit: "cup",
        unitLong: "cup",
        unitShort: "cup",
        aisle: "Milk, Eggs, Other Dairy",
        name: "butter",
        original: "cup organic butter, softened",
        originalName: "organic butter, softened",
        meta: ["organic", "softened"],
        image: "https://img.spoonacular.com/ingredients_100x100/butter-sliced.jpg",
      },
      {
        id: 1123,
        amount: 2,
        unit: "large",
        unitLong: "larges",
        unitShort: "large",
        aisle: "Milk, Eggs, Other Dairy",
        name: "eggs",
        original: "2 large organic eggs",
        originalName: "organic eggs",
        meta: ["organic"],
        image: "https://img.spoonacular.com/ingredients_100x100/egg.png",
      },
      {
        id: 1077,
        amount: 0.5,
        unit: "cup",
        unitLong: "cups",
        unitShort: "cup",
        aisle: "Milk, Eggs, Other Dairy",
        name: "milk",
        original: "1/2 cup organic milk",
        originalName: "organic milk",
        meta: ["organic"],
        image: "https://img.spoonacular.com/ingredients_100x100/milk.png",
      },
    ],
    unusedIngredients: [
      {
        id: 10819297,
        amount: 1,
        unit: "serving",
        unitLong: "serving",
        unitShort: "serving",
        aisle: "Nut butters, Jams, and Honey",
        name: "strawberry jam",
        original: "strawberry jam",
        originalName: "strawberry jam",
        meta: [],
        image: "https://img.spoonacular.com/ingredients_100x100/strawberry-jam.png",
      },
      {
        id: 11124,
        amount: 1,
        unit: "serving",
        unitLong: "serving",
        unitShort: "serving",
        aisle: "Produce",
        name: "carrots",
        original: "carrots",
        originalName: "carrots",
        meta: [],
        image: "https://img.spoonacular.com/ingredients_100x100/sliced-carrot.png",
      },
      {
        id: 11935,
        amount: 1,
        unit: "serving",
        unitLong: "serving",
        unitShort: "serving",
        aisle: "Condiments",
        name: "ketchup",
        original: "ketchup",
        originalName: "ketchup",
        meta: [],
        image: "https://img.spoonacular.com/ingredients_100x100/ketchup.png",
      },
    ],
    likes: 1,
  },
];

export default recipesExample;
